wget http://thinkstats.com/survey.py
wget http://greenteapress.com/thinkstats/2002FemPreg.dat.gz
wget http://greenteapress.com/thinkstats/2002FemResp.dat.gz
wget http://greenteapress.com/thinkstats/2002Male.dat.gz
wget http://thinkstats.com/thinkstats.py
wget http://thinkstats.com/Pmf.py
wget http://thinkstats.com/myplot.py
wget http://thinkstats.com/descriptive.py
wget http://thinkstats.com/risk.py
wget http://thinkstats.com/conditional.py
